apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicelogin
spec:
  replicas: 3
  selector:
    matchLabels:
      role: servicelogin
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: servicelogin
    spec:
      containers:
      - name: servicelogin
        image: blocnotas/servicelogin
        ports:
        - containerPort: 3900