apiVersion: v1
kind: Service
metadata:
  name: serviceLogin-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3900
      targetPort: 3900
      name: http
  selector:
    role: serviceLogin