apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceCrud
spec:
  replicas: 3
  selector:
    matchLabels:
      role: serviceCrud
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: serviceCrud
    spec:
      containers:
      - name: serviceCrud
        image: blocnotas/serviceCrud
        ports:
        - containerPort: 3800