apiVersion: v1
kind: Service
metadata:
  name: backend-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3800
      targetPort: 3800
      name: http
  selector:
    role: backend